// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCISRpmSqQo-FH5-bJ98r_B2d9oxEW1vbk',
    appId: '1:372311754513:web:1423137f30ec78d61faeb0',
    messagingSenderId: '372311754513',
    projectId: 'whisper-e653b',
    authDomain: 'whisper-e653b.firebaseapp.com',
    storageBucket: 'whisper-e653b.firebasestorage.app',
    measurementId: 'G-7SXVS01S63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN4bGTd2gHPcrCvVpXqbUxYK1fSoYJDc0',
    appId: '1:372311754513:android:69ad8f929449e8ad1faeb0',
    messagingSenderId: '372311754513',
    projectId: 'whisper-e653b',
    storageBucket: 'whisper-e653b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1zip2aSMZ21vOZN6Ao5cw5BFIpNkiASM',
    appId: '1:372311754513:ios:b8193e00e8e5b2241faeb0',
    messagingSenderId: '372311754513',
    projectId: 'whisper-e653b',
    storageBucket: 'whisper-e653b.firebasestorage.app',
    iosBundleId: 'com.example.whispr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1zip2aSMZ21vOZN6Ao5cw5BFIpNkiASM',
    appId: '1:372311754513:ios:b8193e00e8e5b2241faeb0',
    messagingSenderId: '372311754513',
    projectId: 'whisper-e653b',
    storageBucket: 'whisper-e653b.firebasestorage.app',
    iosBundleId: 'com.example.whispr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCISRpmSqQo-FH5-bJ98r_B2d9oxEW1vbk',
    appId: '1:372311754513:web:c53cb5cfb7d02d391faeb0',
    messagingSenderId: '372311754513',
    projectId: 'whisper-e653b',
    authDomain: 'whisper-e653b.firebaseapp.com',
    storageBucket: 'whisper-e653b.firebasestorage.app',
    measurementId: 'G-BF1HPMLX77',
  );
}
